---
- name: master node configurations
  hosts: master
  become: yes
  tasks:
    - name: Ensure necessary directories exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Initialize the Kubernetes cluster
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output

    - name: Debug kubeadm output
      debug:
        var: kubeadm_output.stdout

    - name: Create .kube directory
      file:
        path: "/home/ubuntu/.kube"
        state: directory
        mode: '0755'
        owner: "ubuntu"
        group: "ubuntu"

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/ubuntu/.kube/config"
        remote_src: yes
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'
    - name: Change ownership of the kube config
      file:
        path: "/home/ubuntu/.kube/config"
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'

    - name: Deploy Networking Solution(calico)
      ansible.builtin.command:
        cmd: kubectl apply -f https://docs.projectcalico.org/v3.20/manifests/calico.yaml

    - name: Deploy ingress controller (nginx)
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingressnginx/controller-v0.49.0/deploy/static/provider/baremetal/deploy.yaml
