---
- name: Worker node configurations
  hosts: slaves
  become: yes
  tasks:
    - name: Read join command script from file on Ansible control node
      delegate_to: localhost
      slurp:
        src: "./join_command.sh"
      register: join_command_file

    - name: Decode join command
      set_fact:
        join_command: "{{ join_command_file.content | b64decode | regex_replace('\\\\', '') }}"

    - name: Save join command script on worker
      copy:
        content: |
          #!/bin/bash
          {{ join_command }}
        dest: /tmp/join_command.sh
        mode: '0755'

    - name: Join the Kubernetes cluster
      command: /tmp/join_command.sh
      args:
        creates: /etc/kubernetes/kubelet.conf
